# Generated by Django 3.2.16 on 2023-02-07 23:27

from django.db import migrations



def create_data(apps, schema_editor):
    user = apps.get_model('users_student', 'user')
    user(name="Joe Silver",Family_name="hh", email="joe@email.com", phone="00000000").save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
           migrations.RunPython(create_data),
    ]